name: Rancher Update Service
branding:
  color: blue
  icon: arrow-up-circle
description: An action for updating a service in the Rancher 2.x environment
inputs:
  rancher_url:
    description: Rancher instance URL
    required: true
  rancher_token:
    description: Rancher API access token
    required: true
  cluster_id:
    description: Rancher/Kubernetes Cluster ID
    required: true
  project_id:
    description: Rancher Project ID
    required: true
  namespace:
    description: Rancher/Kubernetes Namespace
    required: true
  deployment:
    description: Deployment/Service within the Namespace
    required: true
  docker_image:
    description: Docker image
    required: true

runs:
  using: node16
  main: main.js
