name: Rancher Update Service
branding:
  color: blue
  icon: arrow-up-circle
description: An action for updating a service in the Rancher 2.x environment
inputs:
  rancher_url:
    description: Rancher instance URL
    required: true
  rancher_token:
    description: Rancher API access token
    required: true
  cluster_id:
    description: Rancher/Kubernetes Cluster ID
    required: true
  namespace:
    description: Rancher/Kubernetes Namespace
    required: true
  kind:
    description: Kind of workload, e.g. deployment (default), cronjob, statefulset, ...
    required: false
    default: 'deployment'
  workload:
    description: Workload (Deployment, CronJob, StatefulSet, ...) within the Namespace
    required: true
  deployment:
    description: Deployment/Service within the Namespace
    deprecationMessage: Use workload instead
    required: false
  container_id:
    description: Container ID within the workload
    required: false
    default: '0'
  docker_image:
    description: Docker image
    required: true

runs:
  using: node20
  main: main.js
