name: Rancher Update Service
branding:
  color: blue
  icon: arrow-up-circle
description: An action for updating a service in the Rancher 2.x environment
inputs:
  rancher_url:
    description: Rancher instance URL
    required: true
  rancher_token:
    description: Rancher API access token
    required: true
  cluster_id:
    description: Rancher/Kubernetes Cluster ID
    required: true
  namespace:
    description: Rancher/Kubernetes Namespace
    required: true
  workloads:
    description: |
      Workloads (Deployment, CronJob, StatefulSet, ...) within the Namespace
      Can be multiple, separated by commas or spaces or newlines.
      Format: `kind/name` or `kind/name/container` (container defaults to `0`)
    required: true
  docker_image:
    description: Docker image
    required: true
  redeploy:
    description: |
      Whether to redeploy the service after updating the image.
      If set to `true`, the service will be redeployed by adding a timestamp annotation to the pod.
      Does not apply to Jobs or CronJobs.
    required: false
    default: 'false'

runs:
  using: node20
  main: main.js
