name: Rancher Update Service
branding:
  color: blue
  icon: arrow-up-circle
description: An action for updating a service in the rancher 1.6.x environment
inputs:
  rancher_url:
    description: Rancher instance url
    required: true
  rancher_access:
    description: Rancher access rancher
    required: true
  rancher_key:
    description: Rancher api key
    required: true
  project_id:
    description: Id of the used rancher project
    required: true
  stack_name:
    description: Name of the stack which is associated with the service
    required: true
  service_name:
    description: Name of the service which should be updated
    required: true
  docker_image:
    description: Name of the docker image which is used for updating
    required: true
  retry_count:
    description: Maximum number of retries waiting for upgrade
    required: false
    default: '10'
  retry_delay:
    description: Timeout before retry waiting for upgrade
    required: false
    default: '5'
outputs:
  result:
    description: Boolean which indicates if the action was successful or not

runs:
  using: node16
  main: main.js
